### ISSUE TITLE
After 10.24 release args_base64 became unencoded

### ISSUE THREAD

**Issue by AngelBlock** [near/near-indexer-for-explorer#305] opened 2022-09-11 09:32 UTC
prior latest release `select args ->> 'args_base64' from transaction_actions where transaction_hash = '4nTytkttSSs4rndMccmnxXEF5Zi9KwAdFFhiz3ePpeeg';` would be returning base64 string `eyJhbW91bnQiOiI4NDIwMDAwMDAwMDAwMDAwMDAwMDAwMDAifQ==` 

after latest update we started to notice all new transactions indexed the way, the same query will return:

`<span class="error">[123, 34, 97, 109, 111, 117, 110, 116, 34, 58, 34, 56, 52, 50, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 34, 125]</span>`

**Comment by khorolets** [comment] 2022-09-12 09:06
Hey there! Thanks for bringing it up. I haven't succeeded in my attempt to reproduce the issue you're reporting.

I've taken the recent `FUNCTION_CALL` transaction and checked the DB



```
select args ->> 'args_base64'  from transaction_actions where transaction_hash = '6GqQzrdsAgExNt2KGdpXiRSs6MW7YCTXMTVCMsgv9exR';
                           ?column?
--------------------------------------------------------------
 eyJwaXhlbHMiOlt7IngiOjgsInkiOjMsImNvbG9yIjoxNTg1OTk2N31dfQ==
```

I've checked a couple of transactions randomly and all of them had base64 encoded `args_base64`

Could you provide steps to reproduce, please?

**Comment by frol** [comment] 2022-09-13 11:10
@khorolets It is only fine on mainnet due to the fact that we run redundant nodes. See the change: https://github.com/near/nearcore/commit/8e9be9fff4d520993c81b0e3738c0f223a9538c0#diff-1e4fc99d32e48420a9bd37050fa1412758cba37825851edea40cbdfcab406944L852. It is similar in nature to the DeployContract code hash issue that we faced before. base64 encoding was replaced with proper serialization configuration, but that broke on indexer for explorer side as we just dump Vec<> now. Please, fix it.

**Comment by frol** [comment] 2022-09-13 11:27
@khorolets see testnet database:

```
select * from action_receipt_actions where receipt_id = 'F9AfqcZKxBrBKq597jRULLM7JtYYEsxk127xCQQELrjR';
```

<img width="1503" alt="image" src="https://user-images.githubusercontent.com/304265/189889484-c0e492c1-0c1d-4016-9fd3-f4569760bf9f.png">

Please, re-index the database after the fix.

**Comment by khorolets** [comment] 2022-09-13 16:05
Resolved by #306. I am going to cut a new release with this fix included.

**Closed** 2022-09-13 16:05 UTC
Labels: bug

**Comment by AngelBlock** [comment] 2022-09-14 15:47
@frol @khorolets

**Comment by AngelBlock** [comment] 2022-09-14 15:48
this transaction s from September 10, 2022 at 1:01:37am

**Comment by frol** [comment] 2022-09-14 15:52
@AngelBlock re-index does not override data by default, so you will need to drop those records. We can also consider having a flag to force overrides

**Comment by AngelBlock** [comment] 2022-09-14 15:54
@frol I see I though it was taken care of, I'll do truncate the data. But flag makes sense, in combination of `sync-from-interruption`
